const products = [
  {
    id: 1,
    name: "ACER ASPIRE TC-780 Intel Core I7 GeForce GT1050 23-inches LED Windows 10",
    description:
      "Free your creativity! Even demanding tasks like editing home videos and compiling photo albums are easy with the Aspire T Series’ new-generation performance and easy expandability.",
    price: 36995,
    brand: "ASROCK",
    image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575553061/mlugiouejvzbb0lhfi7e.jpg",
    category: ["Computers", "Desktop pc"],
    slug: "acer-aspire-tc-780-inter-core-i7",
    reviews: 10,
  },
  {
    id: 2,
    name: "ASUS Laptop 14 X409FA",
    description:
      "ASUS X409 is the entry-level laptop that delivers powerful performance and immersive visuals. Its NanoEdge display boasts wide 178° viewing angles and a matte anti-glare coating for a truly engaging experience",
    price: 27995,
    brand: "ASROCK",
    image:
      "https://costpriceuae.com/28-home_default/asus-laptop-14-x409fa-core-i3-8145u-21-ram-4gb.jpg",
    category: ["Computers", "Notebooks"],
    slug: "asus-laptop-14-x409fa",
    reviews: 12,
  },
  {
    id: 3,
    name: "PCX Cobalt Custom Entry C – Customizable Mini PC (NUC6CAYH)",
    description:
      "A complete mini PC built with a quad-core Intel® Celeron® processor, featuring cost-efficient Intel-level performance.",
    price: 8495,
    brand: "ASROCK",
    image: "https://res.cloudinary.com/deiecmpac/image/upload/v1575553538/pvxxxdvjgbf0bdmhg2s6.jpg",
    category: ["Computers", "Mini pc"],
    slug: "pcs-cobalt-custom-entry-c",
    reviews: 9,
  },
  {
    id: 4,
    name: "PCX Cobalt 8 Custom Mainstream – Customizable Mini PC (NUC8i3BEH)",
    description:
      "Small but powerful mini PC is designed for vivid entertainment and casual gaming, digital signage, and the workplace.",
    price: 16550,
    brand: "ASROCK",
    image: "https://res.cloudinary.com/deiecmpac/image/upload/v1575554533/htbw6azc6xit6ifvjlvu.jpg",
    category: ["Computers", "Mini pc"],
    slug: "pcs-cobalt-8-custom-mainstream",
    reviews: 12,
  },
  {
    id: 5,
    name: "WINDOWS 10 PROFESSIONAL 64-BIT",
    description:
      "With Windows 10 Pro, you’ve got a great business partner. It has all the features of Windows 10 Home, plus important business functionality for encryption, remote log-in, creating virtual machines, and more. Get fast start-ups, a familiar yet expanded Start menu, and great new ways to get stuff done, plus innovative features like an all-new browser built for online action.",
    price: 12400,
    brand: "ASROCK",
    image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575256402/xcltu5pxdpucwlwyabxv.jpg",
    category: ["Computers", "Software"],
    slug: "windows-10-professional-64-bit",
    reviews: 12,
  },
  //   {
  //     id: 6,
  //     name: "Kaspersky Internet Security 2019 3 Devices 2 Years Protection",
  //     description:
  //       "Whatever you do online – on your PC, Mac & Android devices – our advanced, one-license security suite helps protect you from malware, webcam spies, financial scammers & more.",
  //     price: 2695,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575555787/d0sqmtzbpmm9fwqqz77x.jpg",
  //     category: ["Computers", "Software"],
  //   },
  //   {
  //     id: 7,
  //     name: "Office Home & Business 2019 for PC or Mac",
  //     description:
  //       "For families and small businesses who want classic Office apps and email installed on one PC or Mac for use at home or work. Classic versions of Office apps including Word, Excel, PowerPoint. OneNote for Windows 10.",
  //     price: 14500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575556188/yful95tirpm0qosl9cn9.jpg",
  //     category: ["Computers", "Software"],
  //   },
  //   {
  //     id: 8,
  //     name: "AMD Ryzen 5 3600X",
  //     description: "Serious High-Definition Gaming Everyone deserves a powerful processor.",
  //     price: 14200,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575007788/skmhcv5dvvddrxjqra7b.jpg",
  //     category: ["Components", "Processor"],
  //   },
  //   {
  //     id: 9,
  //     name: "AMD Ryzen 9 3900X Processor",
  //     description:
  //       "Higher speeds. More memory. Wider bandwidth. You must push every lever, squeeze every ounce, and leave nothing on the table. AMD’s 3rd Gen Ryzen™ processor was designed to break expectations and set a new standard for high-performance processors.",
  //     price: 28900,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575008287/ri8gdpketadqr78jcmpm.jpg",
  //     category: ["Components", "Processor"],
  //   },
  //   {
  //     id: 10,
  //     name: "AMD A6-7480 Dual-Core 3.8 GHz Socket FM2+ 65W AD7480ACABBOX Desktop Processor Radeon R5",
  //     description:
  //       "FOR BUNDLING ONLY: This processor must be bought together with any compatible motherboard.",
  //     price: 28900,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575008611/rfb7vwbybsnwgzhilukp.jpg",
  //     category: ["Components", "Processor"],
  //   },
  //   {
  //     id: 11,
  //     name: "Intel Celeron G4900 Processor (2M Cache, 3.10 GHz)",
  //     description: "Intel Celeron G4900 Processor (2M Cache, 3.10 GHz)",
  //     price: 2300,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575009003/suhncjuzl4c1bdml6t2a.jpg",
  //     category: ["Components", "Processor"],
  //   },
  //   {
  //     id: 12,
  //     name: "Intel Core i3-9100F Processor (6M Cache, up to 4.20 GHz)",
  //     description:
  //       "Core i3-9100F is a 64-bit quad-core entry-level performance x86 desktop microprocessor introduced by Intel in early 2019. This chip, which is based on the Coffee Lake microarchitecture, is fabricated on Intel’s 3rd generation 14 nm++ process. This processor, which has a base frequency of 3.6 GHz with a TDP of 65 Watts and a turbo boost of up to 4.2. This chip supports up to 64 GiB of dual-channel…",
  //     price: 4700,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575009237/mi8eupyb1tvmvvs8fec8.jpg",
  //     category: ["Components", "Processor"],
  //   },
  //   {
  //     id: 13,
  //     name: "Intel Core i5-9400 Processor (9M Cache, up to 4.10 GHz)",
  //     description:
  //       "With the power and responsiveness of Intel® Turbo Boost Technology 2.01 2 you can spend more time doing and less time waiting. Create, edit, and share 4K content with ease, and enjoy immersive, full-screen 4K and 360 experiences.",
  //     price: 10350,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575009626/d50wug62kqtlpcfszmro.jpg",
  //     category: ["Components", "Processor"],
  //   },
  //   {
  //     id: 14,
  //     name: "ASUS STRIX Z370-F GAMING Motherboard",
  //     description:
  //       "Intel Z370 ATX gaming motherboard with Aura Sync RGB LED lighting, DDR4 4000MHz support, dual M.2, SATA 6Gbps and USB 3.1 Gen 2 connectors",
  //     price: 11250,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575007180/bz4czaa18faqtmkutxmu.jpg",
  //     category: ["Components", "Motherboard"],
  //   },
  //   {
  //     id: 15,
  //     name: "Gigabyte GA-F2A68HM-S1 A68H FM2+ mATX Motherboard",
  //     description:
  //       "Socket FM2+ supports AMD FM2+/FM2 A-series APU GIGABYTE Ultra Durable™ Technology Dedicated audio hardware zone with Audio Noise Guard design Native USB 3.0 and SATA3 ports with RAID support GIGABYTE UEFI BIOS GIGABYTE On/Off Charge™ for USB devices Solid capacitors design for APU VRM",
  //     price: 2750,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575134386/fxkoxwzsevdutdmin2vx.webp",
  //     category: ["Components", "Motherboard"],
  //   },
  //   {
  //     id: 16,
  //     name: "ASUS TUF X570-PLUS GAMING WI-FI Motherboard",
  //     description:
  //       "AMD AM4 X570 ATX gaming motherboard with PCIe 4.0, dual M.2, Wi-Fi, 12+2 with Dr. MOS power stage, HDMI, DP, SATA 6Gb/s, USB 3.2 Gen 2 and Aura Sync RGB lighting AMD AM4 Socket: Ready for 2nd and 3rd Gen AMD RyzenTM processors Enhanced Power Solution: Military-grade TUF components, ProCool socket and Digi+ VRM for maximum durability Comprehensive Cooling: Active PCH heatsink, VRM heatsink, M.2 he…",
  //     price: 12000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575138306/bjqgyepg9vftg8mod9sd.jpg",
  //     category: ["Components", "Motherboard"],
  //   },
  //   {
  //     id: 17,
  //     name: "MSI Z390-A PRO Motherboard",
  //     description:
  //       "Inspired from architectural design with the extended heatsink for having better thermal solution; also Intel CNVi ready, Core Boost, DDR4 Boost, Core Boost, Turbo M.2 and USB 3.1 Gen2 connector",
  //     price: 2400,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575138810/izyd5n8r11737ripliem.jpg",
  //     category: ["Components", "Motherboard"],
  //   },
  //   {
  //     id: 18,
  //     name: "ASUS STRIX Z390H GAMING",
  //     description:
  //       "Fully command your gaming experience on 9th generation Intel Core processors with the ROG Strix Z390-H Gaming featuring 5-Way Optimization for dynamic system control with AI overclocking. Dual M.2, Gigabit LAN and USB 3.1 Gen2 deliver maximum connectivity speeds while ASUS OptiMem II ensures better DRAM overclocking stability.",
  //     price: 11600,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575139377/i92gsbzgksqsouztd8oz.jpg",
  //     category: ["Components", "Motherboard"],
  //   },
  //   {
  //     id: 19,
  //     name: "INNO3D GeForce RTX 2080 SUPER GAMING OC X3 8GB GDDR6 256-bit Graphics Card (N208S3-08D6X-1180VA24)",
  //     description:
  //       "The NVIDIA® GeForce® RTX 2080 SUPER™ is powered by the award-winning NVIDIA Turing™ architecture with more cores, higher clocks, and faster memory for ultimate performance and incredible new levels of realism. It’s time to gear up and get super powers.",
  //     price: 42750,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575006684/kptkc8e8fyrihktgrwvm.png",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 20,
  //     name: "INNO3D GeForce RTX 2070 SUPER TWIN X2 OC 8GB GDDR6 256-bit Graphics Card (N207S2-08D6X-11801167)",
  //     description:
  //       "The NVIDIA® GeForce® RTX 2070 SUPER™ is powered by the award-winning NVIDIA Turing™ architecture and has a superfast GPU with more cores and faster clocks to unleash your creative productivity and gaming dominance. It’s time to gear up and get super powers.",
  //     price: 29950,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575011622/tpkez4vmu6sarl2wyrce.png",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 21,
  //     name: "INNO3D GeForce RTX 2070 TWIN X2 8GB GDDR6 256-bit Graphics Card (N20702-08D6-1160VA22)",
  //     description:
  //       "The powerful new GeForce RTX™ 2070 takes advantage of the cutting-edge NVIDIA Turing™ architecture to immerse you in incredible realism and performance in the latest games. The future of gaming starts here.",
  //     price: 29270,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575012700/jgqrf3a9blryeqlam698.png",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 22,
  //     name: "Gigabyte Radeon RX VEGA 56 GAMING OC 8G Graphics Card (GV-RXVEGA56GAMING-OC-8GD)",
  //     description:
  //       "Powered by AMD Radeon™ RX VEGA 56 GPU 8GB 2048-bit High Bandwidth Memory (HBM2) WINDFORCE 2X 100mm Fan Cooling System Radeon™ VR Ready Premium Features HDMIx3/ DisplayPortx3 Built for Extreme Overclocking 12+1 Power Phases",
  //     price: 19995,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575129619/mupi6xnktuyesjh3ohhb.jpg",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 23,
  //     name: "MSI Radeon RX 580 Armor OC Graphics Card",
  //     description:
  //       "Core/Memory Boost Clock / Memory Frequency 1366 MHz / 8000 MHz 8GB GDDR5 Armor 2X Thermal Design TORX Fan – Dispersion fan blade: Steep curved blade accelerating the airflow. – Traditional fan blade: Provides steady airflow to massive heat sink below. Zero Frozr: Stopping the fan in low-load situations, keeping a noise-free environment. Advanced Airflow Control technology: Improves cooling effici…",
  //     price: 13500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575129938/wbh4ybsrqihs0ewqkxlt.jpg",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 24,
  //     name: "ASUS RX VEGA 64 STRIX O8G GAMING HBM2 2048BIT",
  //     description:
  //       "Powered by AMD’s Vega architecture, the ASUS ROG Strix RX Vega64 OC Edition delivers jaw-dropping 5K HD gaming experiences featuring 8GB of HBM2 memory. Outshine the competition with Aura Sync RGB lighting while MaxContact and FanConnect II maximize cooling performance. GPU Tweak II allows for simple and intuitive monitoring and control",
  //     price: 51900,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575130379/i8pdln05xcsj6bixb5pc.jpg",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 25,
  //     name: "PowerColor AXRX 580 Red Devil 8GB GDDR5 3DH OC Graphics Card",
  //     description:
  //       "PowerColor Red Devil RX 580 and utilize 8GB of GDDR5 memory with 2304 stream processors and have 2000MHz memory clock speed which is connected via a new high speed 256-bit memory interface",
  //     price: 12900,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575130829/f0remyqzwxdacpxjsb9v.jpg",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 26,
  //     name: "PowerColor AXRX 560 Red Dragon 4GB DDR5 DHA Graphics Card",
  //     description:
  //       "It is based on AMD’s latest GCN 4 architecture designed for GloFo 14nm FinFET that delivers premium VR capability, increased level of performance, smooth VR, seamless support for next-gen gaming monitors and CPU-free game streaming or recording.",
  //     price: 7000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575136992/bd1hatfzqt9yiiinmor7.jpg",
  //     category: ["Components", "Graphics card"],
  //   },
  //   {
  //     id: 27,
  //     name: "G.Skill Trident Z RGB 16GB (8GBx2) 3200MHz DDR4 Dual Channel RGB Memory Kit (F4-3200C16D-16GTZR)",
  //     description:
  //       "Featuring a completely exposed light bar with vibrant RGB LEDs, merged with the award-winning Trident Z heat spreader design, and constructed with the highest quality components, the Trident Z RGB DDR4 memory kit combines the most vivid RGB lighting with uncompromised performance.",
  //     price: 6050,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575355985/miu2fche6rytbmjwawgw.jpg",
  //     category: ["Components", "Memory"],
  //   },
  //   {
  //     id: 28,
  //     name: "G.Skill Ripjaws V 16GB (1X16GB) DDR4-2400MHZ F4-2400C15S-16GVR Memory Module",
  //     description:
  //       "Series: Ripjaws V Memory Type: DDR4 Capacity: 16GB (16GBx1) Multi-Channel Kit: Single Channel Kit Tested Speed: 2400MHz",
  //     price: 3850,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575356669/k2ihibfojuxzcrfcjga0.png",
  //     category: ["Components", "Memory"],
  //   },
  //   {
  //     id: 29,
  //     name: "G.Skill Trident Z RGB 16GB (2X8GB) F4-3000C16D-16GTZR DDR4-3000MHz Memory Module",
  //     description:
  //       "Featuring a completely exposed light bar with vibrant RGB LEDs, merged with the award-winning Trident Z heatspreader design, and constructed with the highest quality components, the Trident Z RGB DDR4 memory kit combines the most vivid RGB lighting with uncompromised performance.",
  //     price: 5900,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575357472/wskkjfl7w8ohzhsou3vq.jpg",
  //     category: ["Components", "Memory"],
  //   },
  //   {
  //     id: 30,
  //     name: "Crucial Ballistix Sport LT BLS8G4D240FSE 8GB DDR4-2400 UDIMM Desktop Memory Module (Red)",
  //     description:
  //       "Speeds start at 2400 MT/s Faster speeds and responsiveness than standard Crucial DDR4 memory Ideal for gamers and performance enthusiasts Four channel memory architecture maximizes data rates Digital camo heat spreader available in white and gray Easy plug-and-play installation Intel® XMP 2.0 profiles for easy configuration Optimized for the latest Intel X99 platforms",
  //     price: 1850,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575358497/tkellyngcu7iusrm3oh8.jpg",
  //     category: ["Components", "Memory"],
  //   },
  //   {
  //     id: 31,
  //     name: "FSP Hyper K 500W 80+APFC Power Supply",
  //     description:
  //       "HYPER K Series Power Supply meets the market mainstream and provides efficiency more than 85%.With the +12 single rail design, SATA array cable, optimized the airflow in case, no-hassle with case side panel.",
  //     price: 2150,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575298985/mhdriblobcrs1mvy2lhr.jpg",
  //     category: ["Components", "Power supply"],
  //   },
  //   {
  //     id: 32,
  //     name: "INTEL 512GB 660P M.2 PCIE NVME 3.0 X4 (6GBPS) (SSDPEKNW512G8X1) SOLID STATE DRIVE",
  //     description:
  //       "Smart technology that accelerates computers' responsiveness. It accesses your computer's frequently used documents, pictures, videos and applications quickly and remembers them after you power off enabling you to create, game, and produce with less waiting.",
  //     price: 12323,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575199201/ohajeyar2phoharw0ddn.jpg",
  //     category: ["Components", "Hard drive"],
  //   },
  //   {
  //     id: 33,
  //     name: "Samsung 500GB 970 EVO PLUS PCIE NVME M.2 (MZ-V7S500BW) Solid State Drive",
  //     description:
  //       "Built using their V-NAND 3-bit MLC flash technology for reliable performance, the 500GB 970 EVO Plus NVMe M.2 Internal SSD from Samsung offers enhanced bandwidth, low latency, and power efficiency. Designed for tech enthusiasts, high-end gamers, and 4K & 3D content designers, it delivers sequential read speeds of up to 3500 MB/s, sequential write speeds of up to 3300 MB/s, an endurance of up to 3…",
  //     price: 7000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575199777/cz25nbdbqhnhda6tjfmq.jpg",
  //     category: ["Components", "Hard drive"],
  //   },
  //   {
  //     id: 34,
  //     name: "Seagate BarraCuda 2TB 3.5-inch Hard Drive (ST2000DM008)",
  //     description:
  //       "Engineered specifically for surveillance security systems Reduced video frame loss Tuned for write-intensive, low bit-rate, high stream-count applications typical to most surveillance applications Prioritized write-operations for maximized surveillance performance TLER & ATA streaming support.",
  //     price: 2600,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575200215/qf7qar4tlf8jj25qy3vq.jpg",
  //     category: ["Components", "Hard drive"],
  //   },
  //   {
  //     id: 35,
  //     name: "WESTERN DIGITAL 1TB PURPLE SATA (WD10PURX)",
  //     description:
  //       "Featuring a completely exposed light bar with vibrant RGB LEDs, merged with the award-winning Trident Z heat spreader design, and constructed with the highest quality components, the Trident Z RGB DDR4 memory kit combines the most vivid RGB lighting with uncompromised performance.",
  //     price: 2500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575295950/oevi9f0sgqfperffscaz.jpg",
  //     category: ["Components", "Hard drive"],
  //   },
  //   {
  //     id: 36,
  //     name: "TOSHIBA 1TB 7200RPM SATA HARD DRIVE",
  //     description:
  //       "7200 RPM performance, 6Gb/s SATA Interface For use in consumer and commercial computers Halogen-free design and power-efficient operation",
  //     price: 2200,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575297661/c1rutgk2q8akpkuvjazn.jpg",
  //     category: ["Components", "Hard drive"],
  //   },
  //   {
  //     id: 37,
  //     name: "XPG BATTLE CRUISER TG ARGB Case",
  //     description:
  //       "Revel in the XPG BATTLECRUISER’s insane cooling capabilities including a high air flow layout, four 120mm ARGB fans as well as support for multiple radiators (up to 360mm ) and a CPU cooler (up to 175mm). The interior layout is designed with future upgrades in mind. It supports an array of motherboards (up to 300mm/E-ATX), graphics cards (up to 400mm ), dual GPUs vertically, and additional fans",
  //     price: 8000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575369319/ctj3mf1jwa1kmoi9rcuq.jpg",
  //     category: ["Components", "Casing"],
  //   },
  //   {
  //     id: 38,
  //     name: "Asus Strix Helios RGB Tempered Glass With Fan Gaming Chassis",
  //     description:
  //       "ROG Strix Helios is a premium mid-tower gaming case with three tempered-glass panels, refined aluminum frame and integrated front-panel RGB lighting. Built-in cable management, including a multifunction cover with GPU braces, keeps the interior sharp and tidy.",
  //     price: 14500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575370510/eihhuiz7nerblcfg7jkt.jpg",
  //     category: ["Components", "Casing"],
  //   },
  //   {
  //     id: 39,
  //     name: "ASUS TUF Gaming GT501 ATX Mid Tower Case",
  //     description:
  //       "Supports up to EATX with metal front panel, tempered-glass side panel, 120 mm RGB fan, 140 mm PWM fan, radiator space reserved, and USB 3.1 Gen 1 Designed to be noticed: Metal front panel with custom TUF Gaming spatter pattern, and 4mm-thick, smoked, tempered-glass side panel to showcase your build’s internals. Mobile battle station: Ergonomic, woven-cotton carry handles enable easy and safe",
  //     price: 6500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575371255/ixclqyy0midnu1iquuur.jpg",
  //     category: ["Components", "Casing"],
  //   },
  //   {
  //     id: 40,
  //     name: "Vikings VKS-30 Shield Tempered Glass Gaming Case with 3 RGB Fans",
  //     description: "Vikings VKS-30 Shield Tempered Glass Gaming Case with 3 RGB Fans",
  //     price: 2200,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575371909/fegzgbvzpbtwryhyewsj.jpg",
  //     category: ["Components", "Casing"],
  //   },
  //   {
  //     id: 41,
  //     name: "Vikings VKS-23 Shield Tempered Glass Gaming Case with 3 RGB Fans",
  //     description: "Vikings VKS-23 Shield Tempered Glass Gaming Case with 3 RGB Fans",
  //     price: 2100,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575372281/ppf62qd1aehdsubeslzt.jpg",
  //     category: ["Components", "Casing"],
  //   },
  //   {
  //     id: 42,
  //     name: "Vikings VKS-22 Shield Tempered Glass Gaming Case with 3 RGB Fans",
  //     description: "Vikings VKS-22 Shield Tempered Glass Gaming Case with 3 RGB Fans",
  //     price: 2100,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575372852/x8ez2lsz9tihgilrttkm.jpg",
  //     category: ["Components", "Casing"],
  //   },
  //   {
  //     id: 43,
  //     name: "Asus Strix Raid Pro 7.1 PCIE Gaming Sound Card",
  //     description:
  //       "Strix Raid Pro is a premium sound card set built with audiophile-grade components to satisfy gamers who demand ultimate audio performance. Strix Raid Pro features rich, immersive, and clear sound with an incredible 116dB signal-to-noise ratio (SNR), and a 600ohm headphone amplifier for deep, tight bass. The simple yet powerful Sonic Studio sound utility and control box provides complete sound card",
  //     price: 7100,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575461048/ktwswdytzabe3oaquagn.jpg",
  //     category: ["Components", "Sound card"],
  //   },
  //   {
  //     id: 44,
  //     name: "LEAD 3D 5.1 USB Sound Card Green",
  //     description:
  //       "Optimizes the sound according to the style of music (such as rock and bass) and offers virtual surround sounds through earphone or stereo sound box. USB 2.0 Sound Controller equipped with standard input and output connectors to add great Mono Input and Stereo Output performance Portable Sound Card For Desktop and Laptop Computer Multi-channels technique, achieve analog Stereo 5.1-channel sound",
  //     price: 200,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575461569/aconsw1ddfg1tkjqvo9u.jpg",
  //     category: ["Components", "Sound card"],
  //   },
  //   {
  //     id: 45,
  //     name: "TP-LINK TG-3468 LAN CARD",
  //     description:
  //       "10/100/1000Mbps PCIe Adapter 32-bit PCIe interface, saving the finite chassis space Wake-on-LAN, convenient to manage over LAN",
  //     price: 600,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575462374/qnsjzol7pamgrdvuphhe.jpg",
  //     category: ["Components", "Lan card"],
  //   },
  //   {
  //     id: 46,
  //     name: "InFocus IN114v XGA DLP Projector",
  //     description:
  //       "Confidently beam your content with the big power and unbeatable value of the InFocus IN114v XGA DLP Projector. These projectors are easy to buy and built to perform with high brightness, high contrast ratio and BrilliantColorTM technology. A compact design and light weight make them as easy to move around as they are to install.",
  //     price: 23800,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575452235/zomrfky5g62cjhpwugrg.jpg",
  //     category: ["Peripherals", "Displays"],
  //   },
  //   {
  //     id: 47,
  //     name: "InFocus IN112xv DLP Projector",
  //     description:
  //       "The IN112xv projector is an incredible value with ultra-long lamp life, high brightness, and outstanding image quality. This value-packed projector is easy to buy and built to perform with HDMI input, high contrast, and BrilliantColor™ technology. Plus, the compact design and light weight makes it as easy to move around as it is to install.",
  //     price: 26000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575453239/acikuhbfwnu8zitxrkse.jpg",
  //     category: ["Peripherals", "Displays"],
  //   },
  //   {
  //     id: 48,
  //     name: "InFocus IN124x XGA DLP Network Projector",
  //     description:
  //       "The InFocus IN124x XGA DLP Network Projector feature high brightness and contrast, low cost, and strong sound − perfect for classrooms, offices or anywhere you need to capture your audience’s attention.",
  //     price: 28500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575453773/bk5d65ornj6armhaemki.jpg",
  //     category: ["Peripherals", "Displays"],
  //   },
  //   {
  //     id: 49,
  //     name: "InFocus IN112v DLP Projector",
  //     description:
  //       "InFocus IN112v Projector Confidently beam your content with the big power and unbeatable value of the InFocus IN110v series. These projectors are easy to buy and built to perform with high brightness, high contrast ratio and BrilliantColorTM technology. A compact design and light weight make them as easy to move around as they are to install",
  //     price: 17900,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575454493/qqfz5iwa3t9s8usrfb3o.jpg",
  //     category: ["Peripherals", "Displays"],
  //   },
  //   {
  //     id: 50,
  //     name: "Acer X118 DLP Projector",
  //     description:
  //       "Acer Essential series projectors are best value projectors ideal for everyday use, at work or home. Make your presentations more compelling and entertainment more exciting with high brightness, high contrast and DLP® 3D Ready2, while adhering to your bottom line.",
  //     price: 16200,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575455034/efjj1q78jdbb73ivndio.jpg",
  //     category: ["Peripherals", "Displays"],
  //   },
  //   {
  //     id: 51,
  //     name: "Logitech G560 LIGHTSYNC RGB DTS:X Surround Sound Gaming Speaker",
  //     description:
  //       "Logitech G560 LIGHTSYNC gaming speakers immerse you in the action with automatic, game-driven RGB lighting effects that react to many popular games.",
  //     price: 10000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575462267/tkqgxj8esscbqnirn7dr.jpg",
  //     category: ["Peripherals", "Audio"],
  //   },
  //   {
  //     id: 52,
  //     name: "Edifier MP100 Mini Bluetooth Speaker (Blue)",
  //     description:
  //       "Bluetooth 4.0 and microSD functionality 20 hour battery life Dust proof & splash proof",
  //     price: 3000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575464693/iaagspfjjeqjpfzlgvun.jpg",
  //     category: ["Peripherals", "Audio"],
  //   },
  //   {
  //     id: 53,
  //     name: "Logitech BRIO 4K Webcam (960-001105)",
  //     description:
  //       "Spectacular video quality up to 4K Look great in any light with HDR and RightLight™ 3 Enhanced security with Windows Hello™",
  //     price: 12000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575466119/crslmapq7meh2gfdepna.jpg",
  //     category: ["Peripherals", "Audio"],
  //   },
  //   {
  //     id: 54,
  //     name: "Hikvision Turbo HD Surveillance Kit with 1TB Seagate SkyHawk (4CH2D2B-2MP-1TB)",
  //     description:
  //       "Package includes: 1 x Hikvision TURBO HD DVR DS-7200HQHI-K1 SERIES 2 x HD 1080p IR Bullet Camera DS-2CE16D0T-IRPF 2 x HD 1080p Indoor IR Turret Camera DS-2CE56D0T-IRPF 1 x 1TB SkyHawk Surveillance Hard Drive",
  //     price: 10000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575514002/soebezkvvvuzcv2d20gr.jpg",
  //     category: ["Peripherals", "Surveillance/cctv"],
  //   },
  //   {
  //     id: 55,
  //     name: "SECURE 3000VA UPS (BLACK)",
  //     description:
  //       "Input Voltage: 220VAC Frequency: 50hz – 60hz Output Voltage: 220VAC Capacity VA/Wattage: 3000VA/2100Watts Transfer Time: ≤10ms including direction time",
  //     price: 5600,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575467152/dyjpumb8zdxdjj1z9t2n.jpg",
  //     category: ["Peripherals", "Ups/avr"],
  //   },
  //   {
  //     id: 56,
  //     name: "SECURE 1500VA UPS (BLACK)",
  //     description:
  //       "Input Voltage: 220VAC Frequency: 50hz – 60hz Output Voltage: 220VAC Capacity VA/Wattage: 1500VA/1050Watts Transfer Time: ≤10ms including direction time",
  //     price: 3000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575467628/oa7ek6yttg1rfbre5kxr.jpg",
  //     category: ["Peripherals", "Ups/avr"],
  //   },
  //   {
  //     id: 57,
  //     name: "SECURE 1000VA UPS (BLACK)",
  //     description:
  //       "Input Voltage: 220VAC Frequency: 50hz – 60hz Output Voltage: 220VAC Capacity VA/Wattage: 1000VA/700Watts Transfer Time: ≤10ms including direction time",
  //     price: 2800,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575467379/mgetb9rawxzz3d7bxnbi.jpg",
  //     category: ["Peripherals", "Ups/avr"],
  //   },
  //   {
  //     id: 58,
  //     name: "SECURE 5000W AVR WITH METER (SVC-5000VA)",
  //     description: "AVR-SECURE 5000W AVR W/MTR (SVC-5000VA)",
  //     price: 7500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575467952/rm6wk9hahpscvua09roj.jpg",
  //     category: ["Peripherals", "Ups/avr"],
  //   },
  //   {
  //     id: 59,
  //     name: "Logitech ConferenceCam Connect (960-001035)",
  //     description:
  //       "Superior video and audio with a compact, 76 mm footprint Works with your meeting and video conferencing applications Plug-free mobility with rechargeable battery",
  //     price: 28000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575465373/jwlrkffembqxxhrihmsu.jpg",
  //     category: ["Peripherals", "Webcam"],
  //   },
  //   {
  //     id: 60,
  //     name: "Logitech BCC950 ConferenceCam (960-000939)",
  //     description:
  //       "All-in-one design is easy to use and saves space Plug-and-play convenience for Windows and Mac Clear HD video and audio at an affordable price",
  //     price: 15000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575465693/cznznodgv0phqzifbjgl.jpg",
  //     category: ["Peripherals", "Webcam"],
  //   },
  //   {
  //     id: 61,
  //     name: "LOGITECH C922 PRO STREAM FULL HD 1080P CAMERA",
  //     description:
  //       "Connect with superior clarity every time you go live on channels like Twitch and YouTube. Stream anything you want in your choice of 1080p or fluid HD 720p at 60fps. Broadcast your gameplay in full HD with integrated background replacement (Powered by Personify), reliable no-drop audio, autofocus, and a 78-degree field of view. Includes free 3-month premium XSplit license.",
  //     price: 5500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575466618/nkofuhlsxi1l3velpdjg.jpg",
  //     category: ["Peripherals", "Webcam"],
  //   },
  //   {
  //     id: 62,
  //     name: "LOGITECH C615 8MP FULL HD WEBCAM",
  //     description:
  //       "Keep everyone up to date with breathtaking Full HD 1080p video recording with autofocus.",
  //     price: 2900,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575466807/ubliffn9zmpkjtpm2cwo.jpg",
  //     category: ["Peripherals", "Webcam"],
  //   },
  //   {
  //     id: 63,
  //     name: "Ubiquiti Unifi 802.11ac PRO Access Point (UAP‑AC‑PRO)",
  //     description:
  //       "The UniFi AC Pro AP features the latest Wi-Fi 802.11ac, 3×3 MIMO technology in a refined industrial design and is ideal for deployment of maximum‑performance wireless networks.",
  //     price: 9000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575527660/l1jamwrkfp7iwa2qcuvw.jpg",
  //     category: ["Net devices", "Access point/range extender"],
  //   },
  //   {
  //     id: 64,
  //     name: "D-Link COVR-C1203 Dual Band Whole Home Mesh Wi-Fi System",
  //     description:
  //       "Introducing Covr, the seamless Wi-Fi solution that’s the perfect fit for your modern home. It blankets every square inch of your home with high speed AC1200 Dual-Band Wi-Fi. With Covr, you enjoy Wi-Fi that’s stable, consistent, and truly seamless.",
  //     price: 11000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575528041/bfrnuhztvz7tbevyxyro.jpg",
  //     category: ["Net devices", "Access point/range extender"],
  //   },
  //   {
  //     id: 65,
  //     name: "D-Link DHP-308AV AV500 PowerLine Mini Adapter",
  //     description:
  //       "PowerLine AV 500 technology for up to 500 Mbps throughput 10/100 LAN port Simple Connect Button for secure connectivity between other PowerLine devices Wall-Plug design for more convenience Quality of Service (QoS) D-Link Green",
  //     price: 2200,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575528333/rq1hbgaop2y3tsxg4bec.jpg",
  //     category: ["Net devices", "Adaptor"],
  //   },
  //   {
  //     id: 66,
  //     name: "D-Link DWA-182 AC1200 Dual-band Wireless USB Adapter",
  //     description: "Super-fast Wireless AC Simple Setup Total Wireless Compatibility",
  //     price: 1600,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575528474/rdjuttcyyxxpofdrxhqw.jpg",
  //     category: ["Net devices", "Adaptor"],
  //   },
  //   {
  //     id: 67,
  //     name: "D-Link DAP-1360 300Mbps N300 Wireless Access Point",
  //     description: "7 Operating Modes Total Security Better Wireless Coverage",
  //     price: 1700,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575529186/jtc02fwobpgguztke746.jpg",
  //     category: ["Net devices", "Adaptor"],
  //   },
  //   {
  //     id: 68,
  //     name: "D-Link DWA-123 Wireless N 150 USB Network Adapter",
  //     description:
  //       "Easy Wireless connectivity for your notebook or desktop computer Compatible with IEEE 802.11n and 802.11g devices including game consoles and digital media players Access a secure wireless network using advanced WPA™ or WPA2™ encryption",
  //     price: 500,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575530480/fxkr2kjy1y1sczffumnq.jpg",
  //     category: ["Net devices", "Adaptor"],
  //   },
  //   {
  //     id: 69,
  //     name: "D-Link DIR-882 AC2600 MU-MIMO Dual-band Gigabit Wireless Router",
  //     description:
  //       "Ultimate Wi-Fi Performance: Stream HD multimedia across your home without interruption using really fast wired and wireless speeds Simultaneous Dual-Band: Deliver faster Wi-Fi speeds of up to 2,533 Mbps (800 Mbps on 2.4GHz + 1,733 Mbps on 5GHz) MU-MIMO: Simultaneous streaming on multiple devices Advanced AC SmartBeam: Bring dead zones back to life by delivering individual beams of bandwidth wh…",
  //     price: 8000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575360782/zr2qven8cv4cuiytlyjc.jpg",
  //     category: ["Net devices", "Router"],
  //   },
  //   {
  //     id: 70,
  //     name: "TP-LINK ARCHER C7 ROUTER",
  //     description:
  //       "Supports 802.11ac standard – the next generation of Wi-Fi Simultaneous 2.4GHz 450Mbps and 5GHz 1300Mbps connections for1.75Gbps of total available bandwidth Dual USB Ports – easily share a printer locally and files & media with networked devices or remotely via FTP server Guest Network Access provides secure Wi-Fi access for guests sharing your home or office network",
  //     price: 5000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575362566/k7vi1zzdjc1qalu4jzgr.jpg",
  //     category: ["Net devices", "Router"],
  //   },
  //   {
  //     id: 71,
  //     name: "D-Link DAP-1665 AC1200 Dual-band Wireless Access Point",
  //     description: "Speed and Range of Wireless AC Multiple Operation Modes Robust Wireless Security",
  //     price: 8000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575528902/gmeox6k7ldoycmymv8hk.jpg",
  //     category: ["Net devices", "Router"],
  //   },
  //   {
  //     id: 72,
  //     name: "Asus RT-N14UHP High Power 3X-Antenna Wireless-N300 3-in-1 Router",
  //     description:
  //       "802.11n single-band Wi-Fi router with detachable high-gain 9dBi antennas for boosted wireless range. USB port for printer networking, storage sharing, or 3G/4G connections.",
  //     price: 2800,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575529541/d2h8whqehoj2ryfehjmr.jpg",
  //     category: ["Net devices", "Router"],
  //   },
  //   {
  //     id: 73,
  //     name: "Asus RT-AC88U AC3100 Dual-band Wireless Gigabit with MU-MIMO Gaming Router",
  //     description:
  //       "AC3100 Dual Band Gigabit WiFi Gaming Router with MU-MIMO, supporting AiProtection network security by Trend Micro, AiMesh for mesh wifi system and WTFast game accelerator",
  //     price: 14000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575530091/ww2shkzzmybvrqw7fpm0.jpg",
  //     category: ["Net devices", "Router"],
  //   },
  //   {
  //     id: 74,
  //     name: "Synology DiskStation DS-1618+ 6-Bay NAS",
  //     description:
  //       "DS1618+ is a 6-bay NAS that provides storage scalability perfect for tech enthusiasts and small- to medium-sized businesses by effortlessly handling workloads. Further boost storage performance with the optional M.2 SSD cache or enhance network speeds by adding a 10 GbE NIC.",
  //     price: 46000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575531138/ujy40cmmaqe94pmuhr0p.jpg",
  //     category: ["Net devices", "Network attached storage"],
  //   },
  //   {
  //     id: 75,
  //     name: "RECCI Velocity RCT-N120 Type-C Data Cable",
  //     description:
  //       "4.5mm diameter OFC wire core 2.4A fast charging and data transmission Air-craft Aluminum Alloy Connector Gold planting process, perfect performance 120 cm woven fiber jacket",
  //     price: 400,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575536658/w0qaugjldasszsafyql1.jpg",
  //     category: ["Accessories", "Cables"],
  //   },
  //   {
  //     id: 76,
  //     name: "REALME C2 2020 3GB+64GB (Diamond Blue)",
  //     description:
  //       "Holding the Realme C2 in the hands, it doesn’t even feel like a budget smartphone even though it’s tagged as one. Made of unibody plastic, the Realme C2 feels solid and sturdy when gripped and rests comfortably against the palm. On the rear, it has a diamond-cut design with a matte-like finish to it, with micro-patterns and a bit of sparkle showing up when the light hits it.",
  //     price: 7000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575541146/sxw3inhezoj2tyejc96o.jpg",
  //     category: ["Gadgets", "Mobile"],
  //   },
  //   {
  //     id: 77,
  //     name: "REALME C2 2020 3GB+64GB (Diamond Black)",
  //     description:
  //       "Holding the Realme C2 in the hands, it doesn’t even feel like a budget smartphone even though it’s tagged as one. Made of unibody plastic, the Realme C2 feels solid and sturdy when gripped and rests comfortably against the palm. On the rear, it has a diamond-cut design with a matte-like finish to it, with micro-patterns and a bit of sparkle showing up when the light hits it.",
  //     price: 7000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575541524/zeasodaamccftx0iw6nc.jpg",
  //     category: ["Gadgets", "Mobile"],
  //   },
  //   {
  //     id: 78,
  //     name: "REALME 5 PRO 8GB+128GB (Crystal Green)",
  //     description:
  //       "The Realme 5 Pro sports an 6.3″ FHD+ LCD display, powered by a Snapdragon 712 SoC and features a quad-camera setup and a 4035mAh battery with VOOC charging via USB Type-C.",
  //     price: 13000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575550644/adxn1ijuixcffqt7f83t.jpg",
  //     category: ["Gadgets", "Mobile"],
  //   },
  //   {
  //     id: 79,
  //     name: "REALME 5 PRO 4GB+128GB ( Crystal Green)",
  //     description:
  //       "The Realme 5 Pro sports an 6.3″ FHD+ LCD display, powered by a Snapdragon 712 SoC and features a quad-camera setup and a 4035mAh battery with VOOC charging via USB Type-C.",
  //     price: 13000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575551188/rmrqtzdlq9ncizwvjkut.jpg",
  //     category: ["Gadgets", "Mobile"],
  //   },
  //   {
  //     id: 80,
  //     name: "REALME 5 4GB+128GB ( Crystal Purple)",
  //     description:
  //       "The Realme 5 sports a 6.5″ HD+ LCD display, powered by a Snapdragon 665 SoC and features a quad-camera setup, a 5000mAh battery with a Micro USB por",
  //     price: 13000,
  //     brand: "ASROCK",
  //     image: "http://res.cloudinary.com/deiecmpac/image/upload/v1575552455/m36i2kbmlut8ie554zox.jpg",
  //     category: ["Gadgets", "Mobile"],
  //   },
];

export default products;
