/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
// import React, { useRef, useState } from "react";
import Image from "next/image";
import { FaShoppingCart, FaHeart } from "react-icons/fa";
import { MdKeyboardArrowDown } from "react-icons/md";
import { BiMinus } from "react-icons/bi";

// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
// import required modules
import { Autoplay, Pagination, Navigation } from "swiper";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

export default function Home() {
  const productCategory = [
    "COMPUTER",
    "COMPONENTS",
    "PERIPERALS",
    "NET DEVICES",
    "ACCESSORIES",
    "GADGETS",
  ];

  const bannerImg = [
    "/assets/images/Banners/Banner1.jpg",
    "/assets/images/Banners/Banner2.jpg",
    "/assets/images/Banners/Banner3.jpg",
    "/assets/images/Banners/Banner4.jpg",
    "/assets/images/Banners/Banner5.jpg",
    "/assets/images/Banners/Banner6.jpg",
  ];

  return (
    <div>
      <Head>
        <title>PC Link | PC Builder and Accessories</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="w-10/12 flex items-center justify-between mx-auto py-3">
          <div className="img-logo">
            <Image src="/assets/images/logo.png" alt="PC Link Logo" width={152} height={45} />
          </div>
          <div className="icons flex">
            <div className="pr-10">
              <FaHeart size={22} />
            </div>
            <div>
              <FaShoppingCart size={22} />
            </div>
          </div>
        </div>
        <div className="bg-amber-500">
          <div className="w-10/12 mx-auto">
            <ul className="flex">
              {productCategory.map((category, i) => {
                return (
                  <li
                    key={i}
                    className="product-category py-3.5 pr-3.5 pl-4 font-medium flex items-center hover:bg-black hover:text-amber-500"
                  >
                    <span className="pr-2.5">{category}</span>
                    <MdKeyboardArrowDown size={22} className="arrow-down-icon" />
                    <BiMinus size={22} className="minus-icon" />
                  </li>
                );
              })}
            </ul>
          </div>
        </div>
      </header>
      <main>
        <Swiper
          spaceBetween={30}
          centeredSlides={true}
          autoplay={{
            delay: 2500,
            disableOnInteraction: false,
          }}
          pagination={{
            clickable: true,
          }}
          navigation={true}
          modules={[Autoplay, Pagination, Navigation]}
          className="mySwiper"
        >
          {bannerImg.map((img, i) => {
            return (
              <SwiperSlide key={i}>
                <img src={img} alt="Banner" width="100%" />
              </SwiperSlide>
            );
          })}
        </Swiper>
      </main>
    </div>
  );
}
