import Head from "next/head";

export default function Home() {
  return (
    <div className="px-2">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-2 flex flex-1 flex-col justify-center items-center min-h-screen">
        <h1 className="m-0 text-7xl text-center text-indigo-500 hover:underline focus:underline">
          asdasds
        </h1>
      </main>
    </div>
  );
}
