/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";

import { FaShoppingCart, FaHeart } from "react-icons/fa";
import { BsFillEyeFill } from "react-icons/bs";
// Import Swiper React components
import { Swiper, SwiperSlide } from "swiper/react";
// import required modules
import { Autoplay, Pagination, Navigation } from "swiper";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";

export default function Home() {
  const bannerImg = [
    "/assets/images/Banners/Banner1.jpg",
    "/assets/images/Banners/Banner2.jpg",
    "/assets/images/Banners/Banner3.jpg",
    "/assets/images/Banners/Banner4.jpg",
    "/assets/images/Banners/Banner5.jpg",
    "/assets/images/Banners/Banner6.jpg",
  ];

  return (
    <div>
      <Head>
        <title>PC Link | PC Builder and Accessories</title>
        <meta name="description" content="Generated by Mike van Peeren" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Swiper
          spaceBetween={30}
          centeredSlides={true}
          autoplay={{
            delay: 2500,
            disableOnInteraction: false,
          }}
          pagination={{
            clickable: true,
          }}
          navigation={true}
          modules={[Autoplay, Pagination, Navigation]}
          className="mySwiper"
        >
          {bannerImg.map((img, i) => {
            return (
              <SwiperSlide key={i}>
                <img src={img} alt="Banner" width="100%" />
              </SwiperSlide>
            );
          })}
        </Swiper>
        <div>
          <h1 className="text-3xl font-bold">Components</h1>
          <div className="shadow-lg shadow-gray-900 max-w-fit">
            <div className="image-container">
              <Image
                src="https://res.cloudinary.com/deiecmpac/image/upload/v1575007788/skmhcv5dvvddrxjqra7b.jpg"
                alt="Product Item"
                width={280}
                height={250}
              />
            </div>
            <div>
              <h1></h1>
              <h3></h3>
              <div className="flex items-center justify-between">
                <button className="flex justify-center border-[1px] text-xs font-bold  py-1 px-2 border-gray-800">
                  <FaShoppingCart size={20} className="mr-2" />
                  <span className="text-gray-600">ADD TO CART</span>
                </button>
                <FaHeart size={20} />
                <BsFillEyeFill size={20} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
